### ISSUE TITLE
provide working example?

### ISSUE THREAD

**Issue by solutionsbyheidi** [eusonlito/jquery.applink#1]
Could you provide a working html example showing the use and having a verified working model for users to work form.  I tried to implement on a website and its not working.  So I took and tried to implement in simple html file/include js and scripts and still can't get it to work.

**Comment by adctive** [comment]
Hi guys, anyone know why I'm getting "applink is not a function" on my website? https://ladies-tailor.ro/ro/content/4-servicii-atelier-de-croitorie-la-comanda-bucuresti

**Comment by eusonlito** [comment]
Remove ` async="" defer="defer"` on script tag `<script async="" defer="defer" src="/themes/lava0135/assets/js/jquery.applink.js.pagespeed.jm.96kltMNPea.js"></script>`

**Comment by adctive** [comment]
I've tried that already and not working. I removed it again to check.
Thanks for helping
