### ISSUE TITLE
how can i use this on drupal platform...

### ISSUE THREAD

**Issue by mubiesam** [eusonlito/jquery.applink#6]
Thanks

**Comment by eusonlito** [comment]
This is a standard jquery plugin. You can use it in any platform. Please, read the README.

**Comment by mubiesam** [comment]
Sorry to bother you, but I'm just a site builder without programming
skill...

Can i pay to you make that as drupal module...
Function Needed: While in the Android browser, user can click a link inside
a Drupal responsive webpage to launch an Android native app on mobile
device.

Thanks,
Sam


2015-04-11 18:32 GMT+08:00 eusonlito <notifications@github.com>:

> This is a standard jquery plugin. You can use it in any platform. Please,
> read the README.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eusonlito/jquery.applink/issues/6#issuecomment-91824162>
> .
>



-- 
揪好玩 Johocen <http://johocen.com> 行銷團隊
夢農場...今天你幫別人圓夢，明天別人幫你圓夢

**Comment by eusonlito** [comment]
Sorry, I don't know as dupal javascript modules works.

1) Download `jquery.applink.js` file.
2) Add script to header `<script src="/js/jquery.applink.js"></script>`
3) On your custom script file add `$('a[data-applink]').applink();` into `$(document).ready(function () {` block.
4) Add `data-applink="fb://profile"` to your links.

Sorry, but it's all that I can help you.

**Comment by mubiesam** [comment]
Got it, thanks

2015-04-12 3:24 GMT+08:00 eusonlito <notifications@github.com>:

> Sorry, I don't know as dupal javascript modules works.
>
> 1) Download jquery.applink.js file.
> 2) Add script to header <script src="/js/jquery.applink.js"></script>
> 3) On your custom script file add $('a[data-applink]').applink(); into $(document).ready(function
> () { block.
> 4) Add data-applink="fb://profile" to your links.
>
> Sorry, but it's all that I can help you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eusonlito/jquery.applink/issues/6#issuecomment-91909342>
> .
>



-- 
揪好玩 Johocen <http://johocen.com> 行銷團隊
夢農場...今天你幫別人圓夢，明天別人幫你圓夢
